version: '3.8'

services:
  rstudio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rstudio
    env_file:
      .env
    restart: always
    volumes:
      - data:/data
    ports:
      - "8787:8787"

volumes:
    data: