version: "3.8"

services:
  rstudio:
    image: sagebionetworks/rstudio:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rstudio
    environment:
      - USER=${RSTUDIO_USER}
      - PASSWORD=${RSTUDIO_PASSWORD}
      - USERID=${RSTUDIO_USERID}
      - GROUPID=${RSTUDIO_GROUPID}
      - ROOT=${RSTUDIO_ROOT}
      - SYNAPSE_TOKEN
    volumes:
      - .:/home/rstudio/awesome-project:rw
    ports:
      - "${HOST_PORT}:8787"